{% set name = "custom-inherit" %}
{% set version = "2.3.1" %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/c/{{ name }}/custom_inherit-{{ version }}.tar.gz"
  sha256: a0d104847b4cc1ae24e00061fc2e11da8766b019bf4c8c753822347366c8c49f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - custom_inherit

about:
  home: "https://github.com/rsokl/custom_inherit"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.md"
  summary: "A Python package that provides customized docstring inheritance schemes between derived classes and their parents."
  doc_url: "https://github.com/rsokl/custom_inherit/blob/master/README.md"

extra:
  recipe-maintainers:
    - rsokl
